const items = [
  { key: '0', name: 'Jos', gender: '♂' },
  { key: '1', name: 'Josette', gender: '♀' },
  { key: '2', name: 'Jos', gender: '♂' },
  { key: '3', name: 'Josette', gender: '♀' },
  { key: '4', name: 'Jos', gender: '♂' },
  { key: '5', name: 'Josette', gender: '♀' },
  { key: '6', name: 'Jos', gender: '♂' },
  { key: '7', name: 'Josette', gender: '♀' },
  { key: '8', name: 'Jos', gender: '♂' },
  { key: '9', name: 'Josette', gender: '♀' },
  { key: '10', name: 'Jos', gender: '♂' },
  { key: '11', name: 'Jos', gender: '♂' },
  { key: '12', name: 'Josette', gender: '♀' },
  { key: '13', name: 'Jos', gender: '♂' },
  { key: '14', name: 'Josette', gender: '♀' },
  { key: '15', name: 'Jos', gender: '♂' },
  { key: '16', name: 'Josette', gender: '♀' },
  { key: '17', name: 'Jos', gender: '♂' },
  { key: '18', name: 'Josette', gender: '♀' },
  { key: '19', name: 'Jos', gender: '♂' },
  { key: '20', name: 'Josette', gender: '♀' },
  { key: '21', name: 'Jos', gender: '♂' },
  { key: '22', name: 'Josette', gender: '♀' },
  { key: '23', name: 'Jos', gender: '♂' },
  { key: '24', name: 'Josette', gender: '♀' },
  { key: '25', name: 'Jos', gender: '♂' },
  { key: '26', name: 'Josette', gender: '♀' },
  { key: '27', name: 'Jos', gender: '♂' },
  { key: '28', name: 'Josette', gender: '♀' },
  { key: '29', name: 'Jos', gender: '♂' },
  { key: '30', name: 'Josette', gender: '♀' },
  { key: '31', name: 'Jos', gender: '♂' },
  { key: '32', name: 'Josette', gender: '♀' },
  { key: '33', name: 'Jos', gender: '♂' },
  { key: '34', name: 'Josette', gender: '♀' },
  { key: '35', name: 'Jos', gender: '♂' },
  { key: '36', name: 'Josette', gender: '♀' },
  { key: '37', name: 'Jos', gender: '♂' },
  { key: '38', name: 'Josette', gender: '♀' },
  { key: '39', name: 'Jos', gender: '♂' },
  { key: '40', name: 'Josette', gender: '♀' },
  { key: '41', name: 'Jos', gender: '♂' },
  { key: '42', name: 'Josette', gender: '♀' },
];

export default items;
