const items = [
  { key: '0', name: 'Ashton Bishal', gender: '♂' },
  { key: '1', name: 'Josette', gender: '♀' },
  { key: '2', name: 'Jos', gender: '♂' },
  { key: '3', name: 'Josette', gender: '♀' },
  { key: '4', name: 'Jos', gender: '♂' },
  { key: '5', name: 'Josette', gender: '♀' },
  { key: '6', name: 'Jos', gender: '♂' },
  { key: '7', name: 'Josette', gender: '♀' },
  { key: '8', name: 'Jos', gender: '♂' },
  { key: '9', name: 'Josette', gender: '♀' },
  { key: '10', name: 'Jos', gender: '♂' },
  { key: '11', name: 'Jos', gender: '♂' },
  { key: '12', name: 'Josette', gender: '♀' },
  { key: '13', name: 'Jos', gender: '♂' },
  { key: '14', name: 'Josette', gender: '♀' },
  { key: '15', name: 'Jos', gender: '♂' },
  { key: '16', name: 'Josette', gender: '♀' },
  { key: '17', name: 'Jos', gender: '♂' },
  { key: '18', name: 'Josette', gender: '♀' },
  { key: '19', name: 'Jos', gender: '♂' },
  { key: '20', name: 'Josette', gender: '♀' },
  { key: '21', name: 'Jos', gender: '♂' },
  { key: '22', name: 'Josette', gender: '♀' },
  { key: '23', name: 'Jos', gender: '♂' },
  { key: '24', name: 'Josette', gender: '♀' },
  { key: '25', name: 'Jos', gender: '♂' },
  { key: '26', name: 'Josette', gender: '♀' },
  { key: '27', name: 'Jos', gender: '♂' },
  { key: '28', name: 'Josette', gender: '♀' },
  { key: '29', name: 'Jos', gender: '♂' },
  { key: '30', name: 'Josette', gender: '♀' },
  { key: '31', name: 'Jos', gender: '♂' },
  { key: '32', name: 'Josette', gender: '♀' },
  { key: '33', name: 'Jos', gender: '♂' },
  { key: '34', name: 'Josette', gender: '♀' },
  { key: '35', name: 'Jos', gender: '♂' },
  { key: '36', name: 'Josette', gender: '♀' },
  { key: '37', name: 'Jos', gender: '♂' },
  { key: '38', name: 'Josette', gender: '♀' },
  { key: '39', name: 'Jos', gender: '♂' },
  { key: '40', name: 'Josette', gender: '♀' },
  { key: '41', name: 'Jos', gender: '♂' },
  { key: '42', name: 'Josette', gender: '♀' }
];

export default items;

const a = [
  { key: '0', name: 'Scott Melia
  ', gender: '♂' },
  { key: '1', name: 'Shin Whitton', gender: '♀' },
  { key: '2', name: 'Adam Sak', gender: '♂' },
  { key: '3', name: 'Cody Hydrick', gender: '♂' },
  { key: '4', name: 'Lee Avant', gender: '♂' },
  { key: '5', name: 'Neil Yowell', gender: '♂' },
  { key: '6', name: 'Brandon Mccollom', gender: '♂' },
  { key: '7', name: 'Esmeralda Raymond', gender: '♀' },
  { key: '8', name: 'Manuela Didonna', gender: '♀' },
  { key: '9', name: 'Emmanuel Allgood', gender: '♂' },
  { key: '10', name: 'Kirby Constable', gender: '♂' },
  { key: '11', name: 'Toney Degree', gender: '♂' },
  { key: '12', name: 'Aletha Correa', gender: '♀' },
  { key: '13', name: 'Flo Shay', gender: '♀' },
  { key: '14', name: 'Gilbert Salser', gender: '♂' },
  { key: '15', name: 'Erminia Gorka', gender: '♀' },
  { key: '16', name: 'Maura Stoudt', gender: '♀' },
  { key: '17', name: 'Mireya Scheerer', gender: '♀' },
  { key: '18', name: 'Arnoldo Billick', gender: '♂' },
  { key: '19', name: 'Jed Todaro', gender: '♂' },
  { key: '20', name: 'Lucien Mucci', gender: '♂' },
  { key: '21', name: 'Emily Mayhan', gender: '♀' },
  { key: '22', name: 'Brock Renshaw', gender: '♂' },
  { key: '23', name: 'Hui Gunnells', gender: '♀' },
  { key: '24', name: 'Clifford Mendell', gender: '♂' },
  { key: '25', name: 'Kenton Sander', gender: '♂' },
  { key: '26', name: 'Edmundo Wainwright', gender: '♂' },
  { key: '27', name: 'Emilio Kirtley', gender: '♂' },
  { key: '28', name: 'Boris Pelchat', gender: '♂' },
  { key: '29', name: 'Elli Palmisano', gender: '♀' },
  { key: '30', name: 'Lonna Vanorden', gender: '♀' },
  { key: '31', name: 'Emelia Wax', gender: '♀' },
  { key: '32', name: 'Akilah Medeiros', gender: '♀' },
  { key: '33', name: 'Burt Bonebrake', gender: '♂' },
  { key: '34', name: 'Darcy Mccullum', gender: '♀' },
  { key: '35', name: 'Janae Pabst', gender: '♀' },
  { key: '36', name: 'Coleman Rispoli', gender: '♂' },
  { key: '37', name: 'Cassidy Lanctot', gender: '♀' },
  { key: '38', name: 'Brunilda Comeaux', gender: '♀' },
  { key: '39', name: 'Jaymie Poteet', gender: '♀' },
  { key: '40', name: 'Coleen Sudderth', gender: '♀' }
];
